spring.application.name=Counsellors-Management-System
spring.datasource.url=jdbc:mysql://localhost:3306/counsellor_portal
spring.datasource.username=Ethun
spring.datasource.password=Ethun@7620


##Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

